// Package domain defines core business entities.
package domain

import "strings"

// =============================================================================
// RFC Classification Headers
// =============================================================================

// ClassificationHeaders contains RFC headers used for email classification.
// These headers are extracted from email providers (Gmail, Outlook) and used
// in Stage 0 of the classification pipeline to filter non-work emails.
type ClassificationHeaders struct {
	// Mailing List Headers (RFC 2369, 2919)
	ListUnsubscribe     string `json:"list_unsubscribe,omitempty"`
	ListUnsubscribePost string `json:"list_unsubscribe_post,omitempty"`
	ListID              string `json:"list_id,omitempty"`

	// Auto/Bulk Headers (RFC 3834)
	Precedence           string `json:"precedence,omitempty"`             // bulk, list, junk
	AutoSubmitted        string `json:"auto_submitted,omitempty"`         // auto-generated, auto-replied
	AutoResponseSuppress string `json:"auto_response_suppress,omitempty"` // Microsoft

	// Mailer Info
	XMailer    string `json:"x_mailer,omitempty"`
	FeedbackID string `json:"feedback_id,omitempty"` // Gmail bulk tracking

	// ESP (Email Service Provider) Detection
	IsMailchimp bool `json:"is_mailchimp,omitempty"`  // X-MC-User
	IsSendGrid  bool `json:"is_sendgrid,omitempty"`   // X-SG-EID
	IsAmazonSES bool `json:"is_amazon_ses,omitempty"` // X-SES-Outgoing
	IsMailgun   bool `json:"is_mailgun,omitempty"`    // X-Mailgun-*
	IsPostmark  bool `json:"is_postmark,omitempty"`   // X-PM-Message-Id
	IsCampaign  bool `json:"is_campaign,omitempty"`   // X-Campaign-*
}

// HasListUnsubscribe returns true if email has unsubscribe header.
func (h *ClassificationHeaders) HasListUnsubscribe() bool {
	return h.ListUnsubscribe != "" || h.ListUnsubscribePost != ""
}

// HasMailingListHeader returns true if email has any mailing list header.
func (h *ClassificationHeaders) HasMailingListHeader() bool {
	return h.HasListUnsubscribe() || h.ListID != ""
}

// IsAutoGenerated returns true if email is auto-generated.
func (h *ClassificationHeaders) IsAutoGenerated() bool {
	if h.AutoSubmitted != "" && strings.ToLower(h.AutoSubmitted) != "no" {
		return true
	}
	return h.AutoResponseSuppress != ""
}

// IsBulkMail returns true if email is marked as bulk mail.
func (h *ClassificationHeaders) IsBulkMail() bool {
	precedence := strings.ToLower(h.Precedence)
	return precedence == "bulk" || precedence == "list" || precedence == "junk"
}

// IsFromESP returns true if email is from an Email Service Provider.
func (h *ClassificationHeaders) IsFromESP() bool {
	return h.IsMailchimp || h.IsSendGrid || h.IsAmazonSES ||
		h.IsMailgun || h.IsPostmark || h.IsCampaign
}

// GetDetectedESP returns the name of detected ESP, or empty string.
func (h *ClassificationHeaders) GetDetectedESP() string {
	switch {
	case h.IsMailchimp:
		return "mailchimp"
	case h.IsSendGrid:
		return "sendgrid"
	case h.IsAmazonSES:
		return "amazon_ses"
	case h.IsMailgun:
		return "mailgun"
	case h.IsPostmark:
		return "postmark"
	case h.IsCampaign:
		return "campaign"
	default:
		return ""
	}
}

// IsMarketingMailer checks if X-Mailer indicates marketing tool.
func (h *ClassificationHeaders) IsMarketingMailer() bool {
	if h.XMailer == "" {
		return false
	}

	mailerLower := strings.ToLower(h.XMailer)
	marketingMailers := []string{
		"mailchimp", "sendgrid", "mailgun", "postmark", "sendinblue",
		"constant contact", "campaign monitor", "hubspot", "marketo",
		"klaviyo", "drip", "convertkit", "aweber", "activecampaign",
		"salesforce", "pardot", "eloqua", "responsys", "braze",
		"iterable", "customer.io", "intercom", "drift",
	}

	for _, m := range marketingMailers {
		if strings.Contains(mailerLower, m) {
			return true
		}
	}
	return false
}

// =============================================================================
// Header Names for Provider Extraction
// =============================================================================

// RFCClassificationHeaderNames returns the list of RFC headers to extract
// from email providers for classification purposes.
var RFCClassificationHeaderNames = []string{
	// Mailing List (RFC 2369, 2919)
	"List-Unsubscribe",
	"List-Unsubscribe-Post",
	"List-Id",

	// Auto/Bulk (RFC 3834)
	"Precedence",
	"Auto-Submitted",
	"X-Auto-Response-Suppress",

	// Mailer Info
	"X-Mailer",
	"Feedback-ID",

	// ESP Specific Headers
	"X-MC-User",           // Mailchimp
	"X-SG-EID",            // SendGrid
	"X-SES-Outgoing",      // Amazon SES
	"X-Mailgun-Variables", // Mailgun
	"X-PM-Message-Id",     // Postmark
	"X-Campaign-ID",       // Campaign emails
}

// AllMetadataHeaders returns all headers needed for sync (basic + RFC classification).
var AllMetadataHeaders = []string{
	// Basic headers
	"From", "To", "Cc", "Bcc", "Subject", "Date",
	"Message-ID", "In-Reply-To", "References", "Content-Type",

	// RFC Classification headers
	"List-Unsubscribe", "List-Unsubscribe-Post", "List-Id",
	"Precedence", "Auto-Submitted", "X-Auto-Response-Suppress",
	"X-Mailer", "Feedback-ID",
	"X-MC-User", "X-SG-EID", "X-SES-Outgoing",
	"X-Mailgun-Variables", "X-PM-Message-Id", "X-Campaign-ID",
}
