-- +migrate Up

-- =============================================================================
-- Todo Projects Table
-- =============================================================================
-- Projects group related todos together (optional)
-- A todo can belong to a project, or exist independently
CREATE TABLE IF NOT EXISTS todo_projects (
    -- Snowflake ID (generated by application)
    id BIGINT PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    -- Basic info
    name VARCHAR(200) NOT NULL,
    description TEXT,

    -- Organization
    area VARCHAR(100),              -- Work, Personal, Finance (life area)
    color VARCHAR(20),              -- Hex color code
    icon VARCHAR(50),               -- Icon identifier

    -- Status
    status VARCHAR(20) DEFAULT 'active',  -- active, completed, archived

    -- Ordering
    sort_order INTEGER DEFAULT 0,

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for projects
CREATE INDEX idx_todo_projects_user ON todo_projects(user_id, status);
CREATE INDEX idx_todo_projects_area ON todo_projects(user_id, area) WHERE area IS NOT NULL;

-- =============================================================================
-- Todos Table
-- =============================================================================
-- Flexible todo structure:
-- - Can belong to a project (project_id)
-- - Can have only an area (area, no project)
-- - Can be completely independent (inbox)
-- - Can be a subtask (parent_id)
CREATE TABLE IF NOT EXISTS todos (
    -- Snowflake ID (generated by application)
    id BIGINT PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    -- === Hierarchy (all optional for flexibility) ===
    project_id BIGINT REFERENCES todo_projects(id) ON DELETE SET NULL,
    area VARCHAR(100),              -- Direct area assignment (when no project)
    parent_id BIGINT REFERENCES todos(id) ON DELETE CASCADE,  -- Subtask

    -- === Basic info ===
    title VARCHAR(500) NOT NULL,
    description TEXT,

    -- === Status & Priority ===
    status VARCHAR(20) DEFAULT 'inbox',   -- inbox, pending, in_progress, waiting, completed, cancelled
    priority INTEGER DEFAULT 3,            -- 1=urgent, 2=high, 3=normal, 4=low

    -- === Schedule ===
    due_date DATE,                  -- Due date (date only)
    due_datetime TIMESTAMPTZ,       -- Due datetime (when exact time needed)
    start_date DATE,                -- Start date (optional)

    -- === Source linking (for auto-created todos) ===
    source_type VARCHAR(30),        -- email, calendar, agent, manual, jira, github, linear
    source_id VARCHAR(255),         -- External ID
    source_url TEXT,                -- URL to original source
    source_metadata JSONB DEFAULT '{}',  -- Additional source-specific data

    -- === Related entities ===
    related_email_id BIGINT,        -- Link to emails table
    related_event_id BIGINT,        -- Link to calendar_events table

    -- === Classification ===
    tags TEXT[],

    -- === Ordering ===
    sort_order INTEGER DEFAULT 0,

    -- === Completion ===
    completed_at TIMESTAMPTZ,

    -- === Timestamps ===
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- =============================================================================
-- Indexes for optimal view queries
-- =============================================================================

-- Inbox view: unassigned todos
CREATE INDEX idx_todos_inbox ON todos(user_id, created_at DESC)
    WHERE project_id IS NULL AND area IS NULL AND status = 'inbox';

-- Today view: todos due today
CREATE INDEX idx_todos_today ON todos(user_id, due_date, priority)
    WHERE status NOT IN ('completed', 'cancelled');

-- Upcoming view: todos with due dates
CREATE INDEX idx_todos_upcoming ON todos(user_id, due_date, due_datetime)
    WHERE due_date IS NOT NULL AND status NOT IN ('completed', 'cancelled');

-- Priority view: by priority then due date
CREATE INDEX idx_todos_priority ON todos(user_id, priority, due_date NULLS LAST)
    WHERE status NOT IN ('completed', 'cancelled');

-- Project view: todos in a specific project
CREATE INDEX idx_todos_project ON todos(project_id, status, sort_order)
    WHERE project_id IS NOT NULL;

-- Area view: todos with direct area assignment (no project)
CREATE INDEX idx_todos_area ON todos(user_id, area, status)
    WHERE project_id IS NULL AND area IS NOT NULL;

-- Subtasks: children of a parent todo
CREATE INDEX idx_todos_parent ON todos(parent_id, sort_order)
    WHERE parent_id IS NOT NULL;

-- Source lookup: find todos created from specific source
CREATE INDEX idx_todos_source ON todos(source_type, source_id)
    WHERE source_type IS NOT NULL;

-- Related email: find todos linked to an email
CREATE INDEX idx_todos_email ON todos(related_email_id)
    WHERE related_email_id IS NOT NULL;

-- Completed view: recently completed
CREATE INDEX idx_todos_completed ON todos(user_id, completed_at DESC)
    WHERE status = 'completed';

-- Waiting view: todos waiting on others
CREATE INDEX idx_todos_waiting ON todos(user_id, updated_at DESC)
    WHERE status = 'waiting';

-- =============================================================================
-- Triggers
-- =============================================================================

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION update_todos_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_todos_updated_at
    BEFORE UPDATE ON todos
    FOR EACH ROW
    EXECUTE FUNCTION update_todos_updated_at();

CREATE TRIGGER trigger_todo_projects_updated_at
    BEFORE UPDATE ON todo_projects
    FOR EACH ROW
    EXECUTE FUNCTION update_todos_updated_at();

-- +migrate Down

DROP TRIGGER IF EXISTS trigger_todo_projects_updated_at ON todo_projects;
DROP TRIGGER IF EXISTS trigger_todos_updated_at ON todos;
DROP FUNCTION IF EXISTS update_todos_updated_at();

DROP TABLE IF EXISTS todos;
DROP TABLE IF EXISTS todo_projects;
